---
  language: ruby
  cache: bundler
  services:
    - mysql
    - postgresql
  rvm:
    - 2.7.0
    - 2.6.5
  os:
    - linux
  before_install:
    - gem install bundler -v 2.1.2
  before_script:
    - psql -c "CREATE USER sample WITH PASSWORD 'password';" -U postgres
    - psql -c "CREATE DATABASE sample;" -U postgres
    - bin/db_setup
